### PR TITLE
Migrating to python3

### LINKED ISSUE #15: Python3 support
Hi there,

as Python2 is not maintained [anymore](https://pythonclock.org/), is there a chance to get this plugin migrated over to Python3? [Fedora](https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3) and [Debian](https://lists.debian.org/debian-python/2019/07/msg00080.html) dropping support for Python2 too.

Many thanks, Jan.

### PR DESCRIPTION
**Pull request by waja**
Converted to python3 with [2to3](http://python3porting.com/2to3.html).
(Closes #15)

### CODE REVIEW

**Comment by bodsch** [comment]
It works on my python3 only systems (archlinux and debian)

**Comment by BornToBeRoot** [comment]
@waja can you rebase the branch (i merged the nc_token-PR) and set the version to 2.0. Then i can merge the PR. Thank!

**Comment by waja** [comment]
I did and I fixed the indentation messed by the last PR.

**Comment by waja** [comment]
@BornToBeRoot I forgot to set version to "2.0" :(

**Comment by BornToBeRoot** [comment]
@waja thanks. I added it.

**Pull request merged**
